###############################################################################
#
# HOW TO USE
#  
# Push any commit to build_windows_dependencies branch, create it if needed
# This will trigger execution of the following workflow
# Generated artifacts can be used to update the dependency package
#
###############################################################################

name: Windows Dependencies

on:
  push:
    branches:
    - build_windows_dependencies
  pull_request:
    branches:
    - build_windows_dependencies

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "Visual Studio 64-bit",
            os: windows-latest,
            triplet: x64-windows
          }
        - {
            name: "Visual Studio 32-bit",
            os: windows-latest,
            triplet: x86-windows
          }

    steps:
    - uses: actions/checkout@v1

    - name: Configure
      id: vars
      shell: cmd
      run: |
        echo ::set-output name=common_options::sdl2-image sdl2-mixer sdl2-net pcre zlib libmad fluidsynth dumb libvorbis portmidi --triplet ${{ matrix.config.triplet }}

    - name: Install
      shell: cmd
      run: |
        xcopy .github\workflows\dumb %VCPKG_INSTALLATION_ROOT%\ports
        vcpkg update
        vcpkg install ${{ steps.vars.outputs.common_options }}

    - name: Export
      shell: cmd
      run: |
        vcpkg export ${{ steps.vars.outputs.common_options }} --zip
        md artifact
        move %VCPKG_INSTALLATION_ROOT%\*.zip artifact

    - name: Upload
      uses: actions/upload-artifact@v1
      with:
        path: artifact
        name: ${{ matrix.config.triplet }}

